### ISSUE TITLE
SKIP button has no effect

### ISSUE THREAD

**Issue by joschro** [opendj/opendj#144]
the "SKIP" buttton on the landing page has no effect.

Using chrome.

**Comment by DanielFroehlich** [comment]
The skip button brings the first slide view to the front, so yes, on the first slide page, it _seems_ to have no effect.

@ortwinschneider , i tried the following in landing.page.html:

```    <ion-buttons slot="end">
            <ion-button color='primary' *ngIf="!slides.isBeginning()" (tap)="skip()">Skip</ion-button>
        </ion-buttons>
```
But that has the effect that the skip button is not show at all (on first slide, this results to false, which hides the button. But then, when sliding, the state of the enclosing toolbar seems not to be updated.

Any idea on how to resolve this? I got the feedback about the "skip" button not working multiple times, so it seems to confuse users, and I would like to fix this.

**Comment by DanielFroehlich** [comment]
maybe need to add something like this:
    <ion-refresher slot="fixed" (ionRefresh)="refresh($event)">
        <ion-refresher-content></ion-refresher-content>
    </ion-refresher>
(seen on playlist.page.html)
