### ISSUE TITLE
Wifi(?) symbol in the upper right corner has no mouse over info

### ISSUE THREAD

**Issue by joschro** [opendj/opendj#145]
It would be nice to have a mouse-over info for the symbol in the upper right corner

**Comment by DanielFroehlich** [comment]
Good point - will add "When visible, you are connected to the server and
receive playlist updates"

Daniel Fröhlich - Senior Solution Architect - M: +49 176 10 24 84 33  - E:
daniel.froehlich@redhat.com
Red Hat GmbH, http://www.de.redhat.com/, Registered seat: Grasbrunn,
Commercial register: Amtsgericht Muenchen, HRB 153243, Managing Directors:
Charles Cachera, Michael O'Neill, Tom Savage, Eric Shander
