### ISSUE TITLE
curator-view: Show Album icon also for currently played song

### ISSUE THREAD

**Issue by joschro** [opendj/opendj#147]
it would be nice to see the album cover also for the currently played song

**Comment by DanielFroehlich** [comment]
The normal users do see it. For Curator/Owner view, It was a sacrifice for
the play/stop buttons.
But there is a re-design for the curator view pending (#85), I will
re-consider then.

[image: image.png]


Daniel Fröhlich - Senior Solution Architect - M: +49 176 10 24 84 33  - E:
daniel.froehlich@redhat.com
Red Hat GmbH, http://www.de.redhat.com/, Registered seat: Grasbrunn,
Commercial register: Amtsgericht Muenchen, HRB 153243, Managing Directors:
Charles Cachera, Michael O'Neill, Tom Savage, Eric Shander
