### ISSUE TITLE
service-playlist implement event persistence using kafka

### ISSUE THREAD

**Issue by DanielFroehlich** [opendj/opendj#16]

**Comment by ortwinschneider** [comment]
I would drop it for MVP

**Comment by DanielFroehlich** [comment]
You are right, it is optional, but I would feel better if we have it. Maybe
on the weekend.....

Daniel Fröhlich - Senior Solution Architect - M: +49 176 10 24 84 33  - E:
daniel.froehlich@redhat.com
Red Hat GmbH, http://www.de.redhat.com/, Registered seat: Grasbrunn,
Commercial register: Amtsgericht Muenchen, HRB 153243, Managing Directors:
Charles Cachera, Michael O'Neill, Tom Savage, Eric Shander
