### ISSUE TITLE
frontend-web - several topics with login page

### ISSUE THREAD

**Issue by DanielFroehlich** [opendj/opendj#22]
1. In firefox, I frequently can enter text into the username field
1. please make the username field default select so that there is a cursor blinking. Or generate a random userName (@ortwinschneider has ideas on how to do so).
1. Please change the text from "Username" to "Welcome! We would like to know who you are, please enter a name. But of course, you can stay anonymous and use an alias:"
1. Center that text (even with line wrapes), it currently breaks the nice symety of the page!
1. Please add "Powerd by OpenShift" Logo at the bottom of the page:
```
<a href="https://www.openshift.com/" title="Powered by OpenShift Online" >
<img alt="Powered by OpenShift Online" src="https://www.openshift.com/images/logos/powered_by_openshift.png"></a>
```

**Comment by col1985** [comment]
Thanks for the feedback. Never tested in Firefox! will check issues. Thanks.
