### ISSUE TITLE
Cleanup new frontend-web

### ISSUE THREAD

**Issue by DanielFroehlich** [opendj/opendj#3]

**Comment by DanielFroehlich** [comment]
@col1985, can you please assigne this ticket to yourself and move it to "
in progress" - it is important to make visible to others what your are working on! 
Thanks
   Dan

**Comment by col1985** [comment]
@DanielFroehlich Sure, skipped my mind. :) 

Currently working on improving user experience for MVP

**Comment by col1985** [comment]
Quick update, refactor going well, current track component took longer than expected. Dancer flow in place. Curator flow in progress.

See updates here, https://github.com/col1985/opendj

**Comment by DanielFroehlich** [comment]
Thx! Please keep in touch with @ortwinschneider  to avoid double work or breaking changes with lots of merge overhead!

**Comment by col1985** [comment]
Sure, repo is in sync with upstream,. I am working on presentation/UI currently.
