### ISSUE TITLE
Show track duration in search (and maybe also in the playlist)

### ISSUE THREAD

**Issue by geektoor** [opendj/opendj#310]
As spotify (and others) usually offer multiple versions of a track, also very lengthy ones, it would be nice to see the track duration in the search already.
It could also be displayed as well on the playlist itself (for songs that aren't currently playing), and yes, i'm aware that we can see "when" a track will play already :) Just as an idea.
Thanks!

**Comment by DanielFroehlich** [comment]
thx for the feedback! Search does now show the duration of the track.

For the playlist, I did not add it. The original idea was to show "when" for the people at the bar to join the dancefloor at the right time. The duration would just overload it, I prefer keep UI as simple as possible for the mainstream user. 
And regarding the "is this the right version of a track" problem: you can always click on the green 
 spotify icon and listen to the track on your device, to verify it is the right one.
