### ISSUE TITLE
Login with chromium webbrowser not working

### ISSUE THREAD

**Issue by j1cken** [opendj/opendj#36]
Multiple clicks on the "Login" button have no outcome if using chromium webbrowser ...

╭─torben@localhost ~/development  
╰─$ rpm -qi chromium
Name        : chromium
Version     : 73.0.3683.86
Release     : 2.fc30
Architecture: x86_64
Install Date: Wed 26 Jun 2019 09:58:42 AM CEST
Group       : Unspecified
Size        : 108720019
License     : BSD and LGPLv2+ and ASL 2.0 and IJG and MIT and GPLv2+ and ISC and OpenSSL and (MPLv1.1 or GPLv2 or LGPLv2)
Signature   : RSA/SHA256, Fri 29 Mar 2019 04:47:35 PM CET, Key ID ef3c111fcfc659b9
Source RPM  : chromium-73.0.3683.86-2.fc30.src.rpm
Build Date  : Wed 27 Mar 2019 10:01:28 PM CET
Build Host  : buildhw-06.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://www.chromium.org/Home
Bug URL     : https://bugz.fedoraproject.org/chromium
Summary     : A WebKit (Blink) powered web browser
Description :
Chromium is an open-source web browser, powered by WebKit (Blink).
╭─torben@localhost ~/development  
╰─$ 

![Screenshot from 2019-06-28 14-33-01](https://user-images.githubusercontent.com/525537/60342715-8076ab80-99b2-11e9-9290-3fe74d968fe4.png)

**Comment by DanielFroehlich** [comment]
could you please re-test with demo.opendj.io?

**Comment by j1cken** [comment]
same with http://demo.opendj.io/login

**Comment by DanielFroehlich** [comment]
Please try again with latest release: [opendj.io/demo](https://www.opendj.io/demo).
I had some problems with the "tap" event in chrome and switched to "click", maybe that fixes the problem.

**Comment by DanielFroehlich** [comment]
I assume it is working now. If not, please  re-open.
