### ISSUE TITLE
Rename "Login" to "Enter" as no real credentials can be provided

### ISSUE THREAD

**Issue by joschro** [opendj/opendj#39]
There is no password needed, so this is rather entering with a Nickname than logging in with a passwort.

**Comment by ortwinschneider** [comment]
Done

**Comment by DanielFroehlich** [comment]
Can we make this "Join Event" please? Enter is also a bit strange. What do
you think?

Daniel Fröhlich - Senior Solution Architect - M: +49 176 10 24 84 33  - E:
daniel.froehlich@redhat.com
Red Hat GmbH, http://www.de.redhat.com/, Registered seat: Grasbrunn,
Commercial register: Amtsgericht Muenchen, HRB 153243, Managing Directors:
Charles Cachera, Michael O'Neill, Tom Savage, Eric Shander

**Comment by DanielFroehlich** [comment]
Fixed by ortwin
