### ISSUE TITLE
As curator, I want to be able to control the volumn of the playback device 

### ISSUE THREAD

**Issue by DanielFroehlich** [opendj/opendj#45]
Suggested by DerHorst during IPO Event

**Comment by ortwinschneider** [comment]
Is the Spotify API providing this? Shouldn't be a big deal...

**Comment by DanielFroehlich** [comment]
Yes, I can control the volume setting in the spotify app via API!


Daniel Fröhlich - Senior Solution Architect - M: +49 176 10 24 84 33  - E:
daniel.froehlich@redhat.com
Red Hat GmbH, http://www.de.redhat.com/, Registered seat: Grasbrunn,
Commercial register: Amtsgericht Muenchen, HRB 153243, Managing Directors:
Charles Cachera, Michael O'Neill, Tom Savage, Eric Shander
