### ISSUE TITLE
Sync Problem in Client

### ISSUE THREAD

**Issue by DanielFroehlich** [opendj/opendj#47]
During IPO Event, it happend several times that client devices were not in sync with the actual playlist. Showing e.g. old track that already disappear, wrong timings (track was pasued /resumed, thus starting from beginning).

Seems to happen when Mobile Client is not used for a while (e.g. screen lock), then unlocked again.
Workaround is a reload of the page, or at next playlist update via websocket (e.g. next track, reorder etc.).

**Comment by DanielFroehlich** [comment]
Is there an HTML event we can subscribe to when the page becomes focus / is visible again? Then we could re-load the playlist  with a sync call again against "..../events/0/playlists/0"

**Comment by ortwinschneider** [comment]
should be fixed...
