### ISSUE TITLE
frontend-web: curator view is lacking track details

### ISSUE THREAD

**Issue by DanielFroehlich** [opendj/opendj#48]
curator view needs to display at least:
- genre
- bpm
- danceability
- engergy
- happyiness

the last three 0-100 values could be simpl string "D:45 E60 H:20"
or fancy: vertical bars in different fill colours, with the letteres D,E,H inside

**Comment by DanielFroehlich** [comment]
@ortwinschneider , that is important for hamburg so curators can do their job!

**Comment by ortwinschneider** [comment]
no problem, where do you want this info to be shown?

**Comment by DanielFroehlich** [comment]
Cool! in the playlist (not for the current track), only for curators. 
simple implmentation: just as text adding to the 2nd line, after the track year
fancy: responsive design - in vertical layout, only genre and bpm is shown. In horizontal layout, more track details.

**Comment by DanielFroehlich** [comment]
"duration_ms": 324173,
    "popularity": 54,
    "provider": "spotify",
    "genre": "acid jazz, downtempo, electronic",
    "danceability": 87,
    "energy": 47,
    "acousticness": 25,
    "instrumentalness": 31,
    "liveness": 13,
    "happiness": 73,
    "bpm": 90,
    "added_by": "tabloidthree-week",
