### ISSUE TITLE
trackDetails fails for certain tracks

### ISSUE THREAD

**Issue by DanielFroehlich** [opendj/opendj#65]
Seen in service-playlist log in demo env.
Need to reproduce and check, e.g. track ID:
1giSAXdhRGm05tPV9hMpsF

**Comment by ortwinschneider** [comment]
I had quite a few tracks that couldn't be added.... (Spotify API returns no track details for track....)

**Comment by DanielFroehlich** [comment]
can you please provide some exact track names so i can check / test with them?

**Comment by DanielFroehlich** [comment]
Yup, that is a bug:

2019-07-01T19:28:58.288] [DEBUG] default - trackDetails eventID=0, trackID=1giSAXdhRGm05tPV9hMpsF
[2019-07-01T19:28:58.288] [DEBUG] default - trackDetails cache miss
(node:4378) UnhandledPromiseRejectionWarning
(node:4378) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4378) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-07-01T19:28:58.575] [ERROR] default - Error: WebapiError: Not Found
[2019-07-01T19:28:58.576] [TRACE] default - trackDetails end
(node:4378) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)

**Comment by DanielFroehlich** [comment]
Happens when there is no audio features result...
