### ISSUE TITLE
Build and Deploy new frontend on openshift

### ISSUE THREAD

**Issue by DanielFroehlich** [opendj/opendj#9]

**Comment by DanielFroehlich** [comment]
Bitte auch auf #7 achten und auf opendj.io/ui/...pfade refactoren, soweit überhaupt notwendiug.

**Comment by ortwinschneider** [comment]
try to go with Jenkins pipeline

**Comment by DanielFroehlich** [comment]
Not sure if jenkins is a good idea - that would then be required in public openshift, and we have only very limited ressources there. I would really prefer S2I also for the frontend.

**Comment by DanielFroehlich** [comment]
looks that the new build procedure does not bundle ioinic for production.
please check!

**Comment by ortwinschneider** [comment]
fixed that for production build. 
But there is another problem with external config (env.js could not be loaded) after the s2i build.

**Comment by DanielFroehlich** [comment]
the env.js 404 not found is an issue with the permissions of the config map, mounting the file into the container. I will try to fix this!
